ccflags-y += -DANDROID_GKI_VFS_EXPORT_ONLY=VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver

obj-$(CONFIG_TOUCHSCREEN_FTS_V3_3) += focaltech_fts_zf.o
focaltech_fts_zf-y += focaltech_core.o
focaltech_fts_zf-y += focaltech_ex_fun.o
focaltech_fts_zf-y += focaltech_ex_mode.o
focaltech_fts_zf-y += focaltech_gesture.o
focaltech_fts_zf-y += focaltech_esdcheck.o
focaltech_fts_zf-y += focaltech_point_report_check.o
focaltech_fts_zf-y += focaltech_i2c.o
focaltech_fts_zf-y += focaltech_flash.o
focaltech_fts_zf-y += focaltech_flash/focaltech_upgrade_ft3518.o
focaltech_fts_zf-y += focaltech_flash/focaltech_upgrade_ft3658u.o
