#obj-y += ams_tmd2755.o
obj-y += tmd2755.o
#obj-y += ams_tmd2755.o ams_tmd2755_prox.o ams_tmd2755_als.o ams_i2c.o
tmd2755-y += ams_tmd2755.o
tmd2755-y += ams_tmd2755_prox.o
tmd2755-y += ams_tmd2755_als.o
tmd2755-y += ams_i2c.o

ccflags-y += $(LOCAL_CFLAG)
LOCAL_CFLAG += -DGPIO_QCOM
LOCAL_CFLAG += -DPRX_DBG
